local c = {
	dark0 = "#0d0e0f",
	dark = "#202020",
	foreground = "#ebdbb2",
	background = "#282828",
	background_dark = "#1d2021",
	background_light = "#32302f",
	medium_gray = "#504945",
	comment = "#665c54",
	gray = "#DEDEDE",
	soft_yellow = "#eebd35",
	soft_green = "#98971a",
	bright_yellow = "#fabd2f",
	orange = "#d65d0e",
	red = "#fb4934",
	error_red = "#cc241d",
	magenta = "#b16286",
	pink = "#D4879C",
	light_blue = "#7fa2ac",
	dark_gray = "#83a598",
	blue_gray = "#458588",
	forest_green = "#689d6a",
	clean_green = "#8ec07c",
	milk = "#E7D7AD",
	none = "NONE",
}

local theme = {
	["@boolean.sql"] = { fg = c.orange },
	["@define.sql"] = { fg = c.red },
	["@keyword.directive.sql"] = { fg = c.red },
	["@comment.sql"] = { fg = c.comment, italic = true },
	["@error.sql"] = { fg = c.red },
	["@punctuation.delimiter.sql"] = { fg = c.foreground },
	["@punctuation.bracket.sql"] = { fg = c.foreground },
	["@punctuation.special.sql"] = { fg = c.foreground },
	["@markup.list.sql"] = { fg = c.foreground },
	["@constant.sql"] = { fg = c.pink, bold = true },
	["@definition.constant.sql"] = { fg = c.pink, bold = true },
	["@constant.builtin.sql"] = { fg = c.pink },
	["@string.sql"] = { fg = c.soft_green, nocombine = true },
	["@character.sql"] = { fg = c.soft_green },
	["@number.sql"] = { fg = c.magenta },
	["@namespace.sql"] = { fg = c.light_blue },
	["@module.sql"] = { fg = c.light_blue },
	["@func.builtin.sql"] = { fg = c.soft_yellow },
	["@function.sql"] = { fg = c.soft_yellow, bold = true },
	["@function.call.sql"] = { fg = c.soft_yellow, bold = true },
	["@function.builtin.sql"] = { fg = c.soft_yellow, bold = true },
	["@func.macro.sql"] = { fg = c.soft_yellow },
	["@parameter.sql"] = { fg = c.blue_gray, nocombine = true },
	["@variable.parameter.sql"] = { fg = c.blue_gray, nocombine = true },
	["@parameter.reference.sql"] = { fg = c.dark_gray },
	["@method.sql"] = { fg = c.soft_yellow, bold = true },
	["@function.method.sql"] = { fg = c.soft_yellow, bold = true },
	["@method.call.sql"] = { fg = c.soft_yellow, bold = true },
	["@function.method.call.sql"] = { fg = c.soft_yellow, bold = true },
	["@field.sql"] = { fg = c.light_blue },
	["@variable.member.sql"] = { fg = c.light_blue },
	["@property.sql"] = { fg = c.blue_gray },
	["@constructor.sql"] = { fg = c.clean_green, nocombine = true },
	["@conditional.sql"] = { fg = c.red },
	["@keyword.conditional.sql"] = { fg = c.red },
	["@repeat.sql"] = { fg = c.red },
	["@keyword.repeat.sql"] = { fg = c.red },
	["@label.sql"] = { fg = c.blue_gray },
	["@keyword.sql"] = { fg = c.red, italic = true },
	["@keyword.return.sql"] = { fg = c.red, italic = true },
	["@keyword.function.sql"] = { fg = c.red, bold = true },
	["@keyword.operator.sql"] = { fg = c.red },
	["@operator.sql"] = { fg = c.foreground },
	["@exception.sql"] = { fg = c.red },
	["@keyword.exception.sql"] = { fg = c.red },
	["@type.sql"] = { fg = c.clean_green },
	["@type.builtin.sql"] = { fg = c.blue_gray },
	["@type.qualifier.sql"] = { fg = c.orange },
	["@storageclass.lifetime.sql"] = { fg = c.orange },
	["@keyword.storage.lifetime.sql"] = { fg = c.orange },
	["@structure.sql"] = { fg = c.blue_gray },
	["@variable.sql"] = { fg = c.light_blue },
	["@variable.builtin.sql"] = { fg = c.blue_gray },
	["@text.sql"] = { fg = c.soft_yellow },
	["@text.strong.sql"] = { fg = c.soft_yellow, bold = true },
	["@text.emphasis.sql"] = { fg = c.soft_yellow, italic = true },
	["@text.underline.sql"] = { fg = c.soft_yellow, underline = true },
	["@text.strike.sql"] = { fg = c.medium_gray, strikethrough = true },
	["@text.title.sql"] = { fg = c.soft_yellow },
	["@text.literal.sql"] = { fg = c.soft_yellow },
	["@markup.sql"] = { fg = c.soft_yellow },
	["@markup.strong.sql"] = { fg = c.soft_yellow, bold = true },
	["@markup.emphasis.sql"] = { fg = c.soft_yellow, italic = true },
	["@markup.underline.sql"] = { fg = c.soft_yellow, underline = true },
	["@markup.strike.sql"] = { fg = c.medium_gray, strikethrough = true },
	["@markup.heading.sql"] = { fg = c.soft_yellow },
	["@markup.raw.sql"] = { fg = c.soft_yellow },
	["@uri.sql"] = { fg = c.soft_yellow },
	["@tag.sql"] = { fg = c.clean_green },
	["@tag.delimiter.sql"] = { fg = c.comment },
	["@tag.attribute.sql"] = { fg = c.soft_yellow },
	--
	-- per language TreeSitter
	["@decorator.sql"] = { fg = c.orange, bold = true },
}

for k, v in pairs(theme) do
	vim.api.nvim_set_hl(0, k, v)
end
